# Dependencies
markdown: redcarpet
highlighter: pygments

# Permalinks
permalink: /posts/:title
timezone: Africa/Casablanca

# Setup
title: Azz-Eddine D.jek
description: 'Keep calm and hack the world'
baseurl:     ''
url:         'https://djekmani.github.io'

author:
  name: 'Azz-Eddine DJEKMANI'
  url: https://twitter.com/dgeeky
  email: djekmani.azzdine@gmail.com

exclude:
  - Gemfile
  - Gemfile.lock
  - bin

gems:
  # - jekyll-mentions
  - jemoji
  - jekyll-redirect-from

sass:
  sass_dir: _scss
  compressed: true

paginate: 5

# Custom vars
show_related_posts: true
animated: true

# Social icons
show_social_icons: true
github_username: djekmani
twitter_username: dgeeky

google_analytics: 
disqus_shortname: azzedinedgeeky

