# Dependencies
markdown: redcarpet
highlighter: pygments

# Permalinks
permalink: /posts/:title
timezone: Africa/Casablanca

# Setup
title: Azz-Eddine D'Blog
description: 'another blog by a security enthusiast'
baseurl:     ''
url:         'https://djekmani.github.io'

author:
  name: 'Azz-Eddine DJEKMANI'
  url: https://twitter.com/dgeeky
  email: azzeddine.djekmani@um5s.net.ma

exclude:
  - Gemfile
  - Gemfile.lock
  - bin

gems:
  # - jekyll-mentions
  - jemoji
  - jekyll-redirect-from

sass:
  sass_dir: _scss
  compressed: true

paginate: 5

# Custom vars
show_related_posts: true
animated: true

# Social icons
show_social_icons: true
github_username: djekmani
twitter_username: djekmani

google_analytics: UA-68101597-1
disqus_shortname: djekmani

excerpt_separator: "\n\n\n\n\n"

